version: '3.8'

services:
  ambev.webapi:
    container_name: ambev_webapi
    image: ${DOCKER_REGISTRY-}ambevapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS:-5000}
    ports:
      - "${ASPNETCORE_HTTP_PORTS:-5000}:${ASPNETCORE_HTTP_PORTS:-5000}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    depends_on:
      - ambev.database
    command: ["sh", "-c", "until pg_isready -h ambev_database -p 5432; do echo waiting for db; sleep 3; done; dotnet Ambev.DeveloperEvaluation.WebApi.dll"]
    networks:
      - ab_net

  ambev.database:
    container_name: ambev_database
    image: postgres:13
    environment:
      POSTGRES_DB: ambev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@0010
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/script-database.sql:/docker-entrypoint-initdb.d/script-database.sql
       
    networks:
      - ab_net

volumes:   
     postgres:

networks:
  ab_net:
    driver: bridge
